#!/bin/bash

set -eux

# setup data/pid dirs, not versioned
mkdir -p ${SNAP_COMMON}/var/run/zookeeper
mkdir -p ${SNAP_COMMON}/var/lib/zookeeper

# setup log dirs, versioned
mkdir -p ${SNAP_DATA}/var/log/zookeeper/txlog

# setup zookeeper config, versioned
mkdir -p ${SNAP_DATA}/etc/zookeeper
cp -a ${SNAP}/etc/zookeeper/conf.dist ${SNAP_DATA}/etc/zookeeper

# if we dont have config yet, link the dist config
ZOOKEEPER_CONF_DIR=${SNAP_DATA}/etc/zookeeper/conf
if [ ! -e ${ZOOKEEPER_CONF_DIR} ]; then
  ln -s conf.dist ${ZOOKEEPER_CONF_DIR}

  # set config to use a SNAP_COMMON data dir
  sed -e "s|/var/lib|${SNAP_COMMON}/var/lib|" -i ${ZOOKEEPER_CONF_DIR}/zoo.cfg
fi
